<table class="table table-bordered">
	<tr>
		<td>{$lang.item_id}</td>
		<td>{$item.id}</td>
	</tr>
	<tr>
		<td>{$lang.title}</td>
		<td>{$item.title}</td>
	</tr>
	<tr>
		<td>{$lang.category}</td>
		<td>{$item.category}</td>
	</tr>
	<tr>
		<td>{$lang.material}</td>
		<td>{$item.material}</td>
	</tr>
	<tr>
		<td>{$lang.region}</td>
		<td>{$item.region}</td>
	</tr>
	<tr>
		<td>{$lang.district}</td>
		<td>{$item.district}</td>
	</tr>
	<tr>
		<td>{$lang.town}</td>
		<td>{$item.town}</td>
	</tr>
	<tr>
		<td>{$lang.digging}</td>
		<td>{$item.digging}</td>
	</tr>
	<tr>
		<td>{$lang.layer}</td>
		<td>{$item.layer}</td>
	</tr>
	<tr>
		<td>{$lang.square}</td>
		<td>{$item.square}</td>
	</tr>
	<tr>
		<td>{$lang.field_number}</td>
		<td>{$item.fieldNumber}</td>
	</tr>
	<tr>
		<td>{$lang.area}</td>
		<td>{$item.area}</td>
	</tr>
	<tr>
		<td>{$lang.homestead}</td>
		<td>{$item.homestead}</td>
	</tr>
	<tr>
		<td>{$lang.gps_coordinates}</td>
		<td>{$item.gps}</td>
	</tr>
	<tr>
		<td>{$lang.dating}</td>
		<td>{$item.dating}</td>
	</tr>
	<tr>
		<td>{$lang.storage}</td>
		<td>{$item.storagePlace}</td>
	</tr>
	<tr>
		<td>{$lang.description}</td>
		<td>{$item.description}</td>
	</tr>
	<tr>
		<td>{$lang.notes}</td>
		<td>{$item.notes}</td>
	</tr>
</table>
