<table class="table table-bordered">
            <tr>
              <td>Идентификатор</td>
              <td>{$item.id}</td>
            </tr>
			<tr>
              <td>Название</td>
              <td>{$item.title}</td>
            </tr>
			<tr>
              <td>Категория</td>
              <td>{$item.category}</td>
            </tr>
			<tr>
              <td>Материал</td>
              <td>{$item.material}</td>
            </tr>
			<tr>
              <td>Область</td>
              <td>{$item.region}</td>
            </tr>
			<tr>
              <td>Район</td>
              <td>{$item.district}</td>
            </tr>
			<tr>
              <td>Населенный пункт</td>
              <td>{$item.town}</td>
            </tr>
			<tr>
              <td>Раскоп</td>
              <td>{$item.digging}</td>
            </tr>
			<tr>
              <td>Пласт</td>
              <td>{$item.layer}</td>
            </tr>
			<tr>
              <td>Квадрат</td>
              <td>{$item.square}</td>
            </tr>
			<tr>
              <td>Полевой номер</td>
              <td>{$item.fieldNumber}</td>
            </tr>
			<tr>
              <td>Участок</td>
              <td>{$item.area}</td>
            </tr>
			<tr>
              <td>Усадьба</td>
              <td>{$item.homestead}</td>
            </tr>
			<tr>
              <td>GPS-координаты</td>
              <td>{$item.gps}</td>
            </tr>
			<tr>
              <td>Датировка</td>
              <td>{$item.dating}</td>
            </tr>
			<tr>
              <td>Датировка</td>
              <td>{$item.dating}</td>
            </tr>
			<tr>
              <td>Место хранения</td>
              <td>{$item.storagePlace}</td>
            </tr>
			<tr>
              <td>Описание</td>
              <td>{$item.description}</td>
            </tr>
			<tr>
              <td>Примечание</td>
              <td>{$item.notes}</td>
            </tr>
          </tbody>
		  </table>